/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import org.apache.thrift.IntRangeSet;
import java.util.Map;
import java.util.HashMap;

public class Equality {
  public static final int EQ = 1;
  public static final int NEQ = 2;
  public static final int LT = 3;
  public static final int LTE = 4;
  public static final int GT = 5;

  public static final IntRangeSet VALID_VALUES = new IntRangeSet(
    EQ, 
    NEQ, 
    LT, 
    LTE, 
    GT );

  public static final Map<Integer, String> VALUES_TO_NAMES = new HashMap<Integer, String>() {{
    put(EQ, "EQ");
    put(NEQ, "NEQ");
    put(LT, "LT");
    put(LTE, "LTE");
    put(GT, "GT");
  }};
}
