/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import org.apache.log4j.Logger;

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;

public class NullComparison implements TBase, java.io.Serializable, Cloneable, Comparable<NullComparison> {
  private static final TStruct STRUCT_DESC = new TStruct("NullComparison");
  private static final TField COL_FIELD_DESC = new TField("col", TType.STRUCT, (short)1);
  private static final TField ISNULL_FIELD_DESC = new TField("isnull", TType.BOOL, (short)2);

  public Column col;
  public static final int COL = 1;
  public boolean isnull;
  public static final int ISNULL = 2;

  private final Isset __isset = new Isset();
  private static final class Isset implements java.io.Serializable {
    public boolean isnull = false;
  }

  public static final Map<Integer, FieldMetaData> metaDataMap = Collections.unmodifiableMap(new HashMap<Integer, FieldMetaData>() {{
    put(COL, new FieldMetaData("col", TFieldRequirementType.DEFAULT, 
        new StructMetaData(TType.STRUCT, Column.class)));
    put(ISNULL, new FieldMetaData("isnull", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.BOOL)));
  }});

  static {
    FieldMetaData.addStructMetaDataMap(NullComparison.class, metaDataMap);
  }

  public NullComparison() {
  }

  public NullComparison(
    Column col,
    boolean isnull)
  {
    this();
    this.col = col;
    this.isnull = isnull;
    this.__isset.isnull = true;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public NullComparison(NullComparison other) {
    if (other.isSetCol()) {
      this.col = new Column(other.col);
    }
    __isset.isnull = other.__isset.isnull;
    this.isnull = other.isnull;
  }

  @Override
  public NullComparison clone() {
    return new NullComparison(this);
  }

  public Column getCol() {
    return this.col;
  }

  public NullComparison setCol(Column col) {
    this.col = col;
    return this;
  }

  public void unsetCol() {
    this.col = null;
  }

  // Returns true if field col is set (has been asigned a value) and false otherwise
  public boolean isSetCol() {
    return this.col != null;
  }

  public void setColIsSet(boolean value) {
    if (!value) {
      this.col = null;
    }
  }

  public boolean isIsnull() {
    return this.isnull;
  }

  public NullComparison setIsnull(boolean isnull) {
    this.isnull = isnull;
    this.__isset.isnull = true;
    return this;
  }

  public void unsetIsnull() {
    this.__isset.isnull = false;
  }

  // Returns true if field isnull is set (has been asigned a value) and false otherwise
  public boolean isSetIsnull() {
    return this.__isset.isnull;
  }

  public void setIsnullIsSet(boolean value) {
    this.__isset.isnull = value;
  }

  public void setFieldValue(int fieldID, Object value) {
    switch (fieldID) {
    case COL:
      if (value == null) {
        unsetCol();
      } else {
        setCol((Column)value);
      }
      break;

    case ISNULL:
      if (value == null) {
        unsetIsnull();
      } else {
        setIsnull((Boolean)value);
      }
      break;

    default:
      throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
    }
  }

  public Object getFieldValue(int fieldID) {
    switch (fieldID) {
    case COL:
      return getCol();

    case ISNULL:
      return new Boolean(isIsnull());

    default:
      throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
    }
  }

  // Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise
  public boolean isSet(int fieldID) {
    switch (fieldID) {
    case COL:
      return isSetCol();
    case ISNULL:
      return isSetIsnull();
    default:
      throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
    }
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof NullComparison)
      return this.equals((NullComparison)that);
    return false;
  }

  public boolean equals(NullComparison that) {
    if (that == null)
      return false;

    boolean this_present_col = true && this.isSetCol();
    boolean that_present_col = true && that.isSetCol();
    if (this_present_col || that_present_col) {
      if (!(this_present_col && that_present_col))
        return false;
      if (!this.col.equals(that.col))
        return false;
    }

    boolean this_present_isnull = true;
    boolean that_present_isnull = true;
    if (this_present_isnull || that_present_isnull) {
      if (!(this_present_isnull && that_present_isnull))
        return false;
      if (this.isnull != that.isnull)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(NullComparison other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    NullComparison typedOther = (NullComparison)other;

    lastComparison = Boolean.valueOf(isSetCol()).compareTo(isSetCol());
    if (lastComparison != 0) {
      return lastComparison;
    }
    lastComparison = TBaseHelper.compareTo(col, typedOther.col);
    if (lastComparison != 0) {
      return lastComparison;
    }
    lastComparison = Boolean.valueOf(isSetIsnull()).compareTo(isSetIsnull());
    if (lastComparison != 0) {
      return lastComparison;
    }
    lastComparison = TBaseHelper.compareTo(isnull, typedOther.isnull);
    if (lastComparison != 0) {
      return lastComparison;
    }
    return 0;
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id)
      {
        case COL:
          if (field.type == TType.STRUCT) {
            this.col = new Column();
            this.col.read(iprot);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case ISNULL:
          if (field.type == TType.BOOL) {
            this.isnull = iprot.readBool();
            this.__isset.isnull = true;
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();


    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.col != null) {
      oprot.writeFieldBegin(COL_FIELD_DESC);
      this.col.write(oprot);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(ISNULL_FIELD_DESC);
    oprot.writeBool(this.isnull);
    oprot.writeFieldEnd();
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("NullComparison(");
    boolean first = true;

    sb.append("col:");
    if (this.col == null) {
      sb.append("null");
    } else {
      sb.append(this.col);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("isnull:");
    sb.append(this.isnull);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check that fields of type enum have valid values
  }

}

