/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import org.apache.thrift.IntRangeSet;
import java.util.Map;
import java.util.HashMap;

public class Order {
  public static final int ASC = 1;
  public static final int DESC = 2;

  public static final IntRangeSet VALID_VALUES = new IntRangeSet(
    ASC, 
    DESC );

  public static final Map<Integer, String> VALUES_TO_NAMES = new HashMap<Integer, String>() {{
    put(ASC, "ASC");
    put(DESC, "DESC");
  }};
}
